#!/bin/ksh
#check for equality

trap_handler() {
	pkill -u $(id -u) -f "$shellweb_cmd" 
	pkill -u $(id -u) -f nc 
	rm -f "$request" 
	rm -f "$response"
	rm -rf "$tmpdir"
	 
}

trap trap_handler EXIT

tmpdir=$(mktemp -dp .)
port=13245
root=$(mktemp -dp $tmpdir)
#root=$(readlink -f $root)
shellweb_cmd="../shellweb -d $root -p $port -v" 
file="$HOME/home.html"
if [ $# -gt 0 ]; then
	file="$1"
else
	file="$HOME/home.html"
fi
echo 1
if [ ! -f "$file" ]; then
	echo "FAIL ==> $0"
	echo 123
	exit 1
fi
request=$(mktemp -p $root)
cp "$file" "$request"
$shellweb_cmd &
sleep 0.1
response=$(mktemp -p $root)
send="${request#$root}"
echo "GET $send HTTP/1.0\r\n\r" | \
	nc -w 1 127.0.0.1 $port | tr -d '\r' >> "$response" 
header=$(head -n 1 $response)
check="HTTP/1.1 200 OK"
if [ x"$header" != x"$check" ]; then
	echo "FAIL ==> $0"
	exit 1
fi

sed -i '1,/^$/ d' "$response"

if  cmp -s "$request" "$response"; then
	echo "OK ==> $0"
else
	echo "FAIL ==> $0"
	exit 1
fi
